### ISSUE TITLE
Somethins doesn't work

### ISSUE THREAD

**Issue by 15863004186sunchi** [vhf/redis-sentinel-docker-example#1]
![image](https://user-images.githubusercontent.com/19647047/56114560-ca471c80-5f93-11e9-85b8-19708d1c90fc.png)

**Comment by fiacc** [comment]
```docker network prune``` via https://github.com/maxking/docker-mailman/issues/85

**Comment by 15863004186sunchi** [comment]
Thank you for your answers.
